---
notes_path: "~/Dropbox/Notes"
build_path: "./dist"
templates_path: "./templates"
site_root_url: "https://notes.musayev.com"
feed_url: "https://notes.musayev.com/feed.xml"
site_name: "Alex Musayev Notes"
author_name: "Alex Musayev"
assets_path: "~/Dropbox/Notes/images"
images_path: "./images"
