require "date"
require "fileutils"
require "http"
require "pry"
require "redcarpet"
require "rouge"
require "rouge/plugins/redcarpet"
require "securerandom"
require "tilt"
require "uri"
require "yaml"

module Notes
  require_relative "./notes/cleanshot_downloader"
  require_relative "./notes/configuration"
  require_relative "./notes/images_cache"
  require_relative "./notes/markdown_renderer"
  require_relative "./notes/note_page"
  require_relative "./notes/note_page_builder"
  require_relative "./notes/page"
  require_relative "./notes/redirect_page"
  require_relative "./notes/site"
  require_relative "./notes/site_builder"
  require_relative "./notes/tag_page"
end
